# Project information
site_name: Cake Wallet Docs
site_url: https://docs.cakewallet.com

# Repository
repo_name: cake-tech/cake_wallet
repo_url: https://github.com/cake-tech/cake_wallet

# Copyright
copyright: Cake Labs LLC

# Configuration
theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep purple
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.instant
    - navigation.indexes
    - announce.dismiss
    - navigation.instant.progress
    - navigation.top
    - navigation.sections

# Extensions
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - admonition
  - pymdownx.blocks.caption
  - abbr
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: cake-tech
      repo: cake-docs
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - meta

# Extras
extra:
  social:
    - icon: simple/x
      link: https://x.com/cakewallet
    - icon: simple/github
      link: https://github.com/cake-tech
  status:
    new: Recently added
    deprecated: Deprecated

nav:
- Home: index.md
- Cryptocurrencies:
  - cryptocurrencies/monero.md
  - cryptocurrencies/bitcoin.md
  - cryptocurrencies/ethereum.md
  - cryptocurrencies/solana.md
  - cryptocurrencies/tron.md
  - cryptocurrencies/bitcoin-cash.md
  - cryptocurrencies/litecoin.md
  - cryptocurrencies/polygon.md
  - cryptocurrencies/nano.md
  - cryptocurrencies/wownero.md
  - cryptocurrencies/haven.md

- Getting Started:
  - "Install":
    - getting-started/index.md
    - "Android":
      - getting-started/android/index.md
      - getting-started/android/obtanium.md
    - "Linux":
      - getting-started/linux/index.md
      - getting-started/linux/tails.md
  - "Setup":
    - getting-started/setup/create-first-wallet.md
    - getting-started/setup/create-another-wallet.md


plugins:
  - search
  - offline
  - glightbox

