# Project information
site_name: Cake Wallet Docs
site_url: https://docs.cakewallet.com

# Repository
repo_name: cake-tech/cake_wallet
repo_url: https://github.com/cake-tech/cake_wallet

# Copyright
copyright: Cake Labs LLC

# Configuration
theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/lightbulb-auto-outline
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: blue
      accent: deep purple

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system preference
      primary: black
      accent: deep purple

  features:
    - navigation.footer
    - navigation.tabs
    - navigation.instant
    - navigation.indexes
    - announce.dismiss
    - navigation.instant.progress
    - navigation.top
    - navigation.sections
    - search.suggest
    - search.share

# Extensions
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - admonition
  - pymdownx.blocks.caption
  - abbr
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: cake-tech
      repo: cake-docs
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - meta

# Extras
extra:
  social:
    - icon: simple/x
      link: https://x.com/cakewallet
    - icon: simple/github
      link: https://github.com/cake-tech
  status:
    new: Recently added
    deprecated: Deprecated

# Navigation
nav:
- Home: index.md

- Get Started:
  - getting-started/index.md
  - Install:
    - Android:
      - getting-started/android/index.md
      - getting-started/android/google-play.md
      - getting-started/android/accrescent.md
      - getting-started/android/obtanium.md
      - getting-started/android/fdroid.md
    - Linux:
      - getting-started/linux/index.md
      - getting-started/linux/tails.md
    - iOS / macOS: getting-started/app-store.md
    - Windows: getting-started/windows.md

  - Setup:
    - getting-started/setup/create-first-wallet.md
    - getting-started/setup/create-another-wallet.md
  - Restore:
    - getting-started/restore/restore-wallet-from-keys-or-seed.md
    - getting-started/restore/restore-wallet-from-backup.md
    - getting-started/restore/restore-wallet-from-qr-code.md
    - getting-started/restore/restore-wallet-from-hardware.md

- Cryptos:
  - cryptocurrencies/index.md
  - cryptocurrencies/monero.md
  - cryptocurrencies/bitcoin.md
  - cryptocurrencies/ethereum.md
  - cryptocurrencies/litecoin.md
  - cryptocurrencies/bitcoin-cash.md
  - cryptocurrencies/polygon.md
  - cryptocurrencies/solana.md
  - cryptocurrencies/tron.md
  - cryptocurrencies/nano.md
  - cryptocurrencies/wownero.md
  - cryptocurrencies/haven.md

- Features:
  - features/index.md
  - Basic Features:
    - basic-features/send-funds.md
    - basic-features/receive-funds.md
    - basic-features/exchange.md
    - basic-features/create-backup.md
  - Advanced features:
    - advanced-features/address-book.md
    - advanced-features/authentication.md
    - advanced-features/change-network-fee.md
    - advanced-features/custom-node.md
    - advanced-features/coin-control.md
    - advanced-features/tor-with-orbot.md
    - advanced-features/special-address-services.md
    - advanced-features/seed-keys.md
    - advanced-features/send-exchange-templates.md
    - advanced-features/disable-features.md

- Cake Pay:
  - cake-pay/index.md
  - cake-pay/buy-gift-card.md
  - cake-pay/faq.md

- Cupcake:
  - cupcake/index.md
  - cupcake/setup.md

- FAQ:
  - faq/index.md
  - faq/connection-issues.md
  - faq/zero-balance.md
  - faq/funds-not-appearing.md
  - faq/errors.md

- Tutorials:
  - tutorials/index.md
  - tutorials/bitcoin-paper-wallet.md
  - tutorials/find-seed-phrase.md
  - tutorials/mobile-hardening.md
  - Setup a monero node: https://guides.monero.com/docs/tutorials/monero-node/
  - tutorials/what-to-do-if-scammed.md

- Support:
  - support/index.md
  - support/buy.md
  - support/cake-pay.md
  - support/swap.md
  - support/receive.md
  - support/sell.md

# - Status: status/index.md

# - cakewallet.com: website/index.md


# Plugins
plugins:
  - search
  - offline
  - glightbox
  # - git-revision-date-localized:
  #     enable_creation_date: true
